language: python
python: 
  - "2.7.8"

install: "pip install -r requirements.txt"

before_script: 
  - autopep8 -ir *
  - flake8 --max-complexity=3 --exclude=*.txt,*.md,*.pyc --max-line-length=200 *

script: 
  - lettuce AceptanceTest
  - cd UnitTest
  - python TestCalculadora.py -v
  - coverage run --branch TestCalculadora.py
  - coverage report -m
